import { db } from '../lib/db';
import { hobbies } from '../lib/db/schema';
import { randomUUID } from 'crypto';

async function addSportsHobbies() {
  try {
    console.log("=== Adding More Sports Hobbies ===\n");

    const newSportsHobbies = [
      {
        id: randomUUID(),
        name: "테니스",
        category: "스포츠",
        description: "라켓으로 공을 주고받는 스포츠. 순발력과 지구력을 기르며 사교 활동으로도 좋습니다.",
        difficulty: 3,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "medium" as const,
        imageUrl: "/tennis.jpg",
        videoUrl: null,
        benefits: ["심폐 지구력", "순발력", "협응력", "사회적 교류"],
        requirements: ["테니스 라켓", "테니스공", "운동화", "운동복"],
        curriculum: [
          { week: 1, title: "기본 자세", content: "라켓 잡는 법과 준비 자세" },
          { week: 2, title: "포핸드 스트로크", content: "기본 포핸드 치기" },
          { week: 3, title: "백핸드 스트로크", content: "백핸드 기술" },
          { week: 4, title: "서브 연습", content: "기본 서브 동작" },
        ],
      },
      {
        id: randomUUID(),
        name: "골프",
        category: "스포츠",
        description: "클럽으로 공을 쳐서 홀에 넣는 스포츠. 집중력과 인내심을 기르며 자연 속에서 즐길 수 있습니다.",
        difficulty: 4,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "high" as const,
        imageUrl: "/golf.jpg",
        videoUrl: null,
        benefits: ["집중력", "인내심", "전신 운동", "사교 활동"],
        requirements: ["골프채 세트", "골프공", "골프화", "골프백"],
        curriculum: [
          { week: 1, title: "그립과 자세", content: "클럽 잡는 법과 어드레스" },
          { week: 2, title: "스윙 기초", content: "백스윙과 다운스윙" },
          { week: 3, title: "아이언 샷", content: "아이언으로 치기" },
          { week: 4, title: "퍼팅", content: "그린에서 퍼팅 연습" },
        ],
      },
      {
        id: randomUUID(),
        name: "탁구",
        category: "스포츠",
        description: "작은 공을 주고받는 실내 스포츠. 반사 신경과 집중력을 키우며 누구나 쉽게 즐길 수 있습니다.",
        difficulty: 2,
        indoorOutdoor: "indoor" as const,
        socialIndividual: "both" as const,
        budget: "low" as const,
        imageUrl: "/table-tennis.jpg",
        videoUrl: null,
        benefits: ["반사신경", "집중력", "눈과 손 협응", "유산소 운동"],
        requirements: ["탁구채", "탁구공", "탁구대"],
        curriculum: [
          { week: 1, title: "기본 자세", content: "라켓 잡는 법과 준비 자세" },
          { week: 2, title: "포핸드 드라이브", content: "기본 공격 기술" },
          { week: 3, title: "백핸드", content: "백핸드 치기" },
          { week: 4, title: "서브와 리시브", content: "서브 넣기와 받기" },
        ],
      },
      {
        id: randomUUID(),
        name: "배구",
        category: "스포츠",
        description: "팀으로 공을 주고받으며 득점하는 스포츠. 협동심과 순발력을 기를 수 있습니다.",
        difficulty: 3,
        indoorOutdoor: "both" as const,
        socialIndividual: "social" as const,
        budget: "low" as const,
        imageUrl: "/volleyball.jpg",
        videoUrl: null,
        benefits: ["협동심", "순발력", "점프력", "팀워크"],
        requirements: ["배구공", "운동화", "운동복", "무릎 보호대"],
        curriculum: [
          { week: 1, title: "기본 자세", content: "리시브 자세와 이동" },
          { week: 2, title: "토스", content: "공 올리기 연습" },
          { week: 3, title: "스파이크", content: "공격 기술" },
          { week: 4, title: "서브", content: "언더핸드와 오버핸드 서브" },
        ],
      },
      {
        id: randomUUID(),
        name: "게이트볼",
        category: "스포츠",
        description: "공을 쳐서 게이트를 통과시키는 시니어 맞춤 스포츠. 전략적 사고와 정확성이 필요합니다.",
        difficulty: 2,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "social" as const,
        budget: "low" as const,
        imageUrl: "/gateball.jpg",
        videoUrl: null,
        benefits: ["전략적 사고", "정확성", "사회적 교류", "적당한 운동량"],
        requirements: ["게이트볼 스틱", "공", "게이트"],
        curriculum: null,
      },
      {
        id: randomUUID(),
        name: "족구",
        category: "스포츠",
        description: "발로 공을 차서 네트 너머로 보내는 한국식 스포츠. 유연성과 협동심을 기를 수 있습니다.",
        difficulty: 3,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "social" as const,
        budget: "low" as const,
        imageUrl: "/jokgu.jpg",
        videoUrl: null,
        benefits: ["유연성", "협동심", "하체 근력", "균형감각"],
        requirements: ["족구공", "네트", "운동화", "운동복"],
        curriculum: [
          { week: 1, title: "기본 동작", content: "공 받기와 차기" },
          { week: 2, title: "스파이크", content: "공격 기술" },
          { week: 3, title: "리시브", content: "수비 자세" },
          { week: 4, title: "팀 플레이", content: "협동 전략" },
        ],
      },
      {
        id: randomUUID(),
        name: "스쿼시",
        category: "스포츠",
        description: "실내 코트에서 벽에 공을 치며 즐기는 스포츠. 순발력과 지구력을 키울 수 있습니다.",
        difficulty: 4,
        indoorOutdoor: "indoor" as const,
        socialIndividual: "both" as const,
        budget: "medium" as const,
        imageUrl: "/squash.jpg",
        videoUrl: null,
        benefits: ["심폐 지구력", "순발력", "민첩성", "전신 운동"],
        requirements: ["스쿼시 라켓", "스쿼시공", "운동화", "보안경"],
        curriculum: [
          { week: 1, title: "기본 자세", content: "라켓 잡는 법과 스윙" },
          { week: 2, title: "포핸드 드라이브", content: "기본 타격" },
          { week: 3, title: "백핸드", content: "백핸드 기술" },
          { week: 4, title: "게임 전략", content: "경기 운영법" },
        ],
      },
      {
        id: randomUUID(),
        name: "승마",
        category: "스포츠",
        description: "말을 타고 달리며 교감하는 스포츠. 균형감각과 정서적 안정을 얻을 수 있습니다.",
        difficulty: 4,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "individual" as const,
        budget: "high" as const,
        imageUrl: "/horse-riding.jpg",
        videoUrl: null,
        benefits: ["균형감각", "정서적 안정", "코어 근력", "동물 교감"],
        requirements: ["헬멧", "승마복", "장화", "승마장 등록"],
        curriculum: [
          { week: 1, title: "말과 친해지기", content: "말 다루는 법" },
          { week: 2, title: "기본 자세", content: "말 위에서 균형 잡기" },
          { week: 3, title: "평보", content: "천천히 걷기" },
          { week: 4, title: "속보", content: "빠르게 달리기" },
        ],
      },
      {
        id: randomUUID(),
        name: "조깅",
        category: "스포츠",
        description: "천천히 달리며 건강을 지키는 유산소 운동. 체력을 기르고 스트레스를 해소할 수 있습니다.",
        difficulty: 1,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "low" as const,
        imageUrl: "/jogging.jpg",
        videoUrl: null,
        benefits: ["심폐 기능", "체중 관리", "스트레스 해소", "지구력"],
        requirements: ["러닝화", "운동복", "물병"],
        curriculum: null,
      },
      {
        id: randomUUID(),
        name: "요트",
        category: "스포츠",
        description: "바람을 이용해 배를 조종하는 수상 스포츠. 자연과 교감하며 모험심을 키울 수 있습니다.",
        difficulty: 5,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "high" as const,
        imageUrl: "/sailing.jpg",
        videoUrl: null,
        benefits: ["문제 해결", "협동심", "자연 교감", "모험심"],
        requirements: ["구명조끼", "요트복", "요트 클럽 등록"],
        curriculum: [
          { week: 1, title: "요트의 구조", content: "돛과 키 이해하기" },
          { week: 2, title: "바람 읽기", content: "바람 방향 파악" },
          { week: 3, title: "기본 조종", content: "직진과 회전" },
          { week: 4, title: "항해 연습", content: "코스 따라 항해하기" },
        ],
      },
      {
        id: randomUUID(),
        name: "인라인 스케이트",
        category: "스포츠",
        description: "바퀴 달린 신발로 달리는 스포츠. 균형감각과 하체 근력을 키울 수 있습니다.",
        difficulty: 3,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "medium" as const,
        imageUrl: "/inline-skating.jpg",
        videoUrl: null,
        benefits: ["균형감각", "하체 근력", "유산소 운동", "재미"],
        requirements: ["인라인 스케이트", "헬멧", "보호대", "운동복"],
        curriculum: [
          { week: 1, title: "기본 자세", content: "균형 잡기와 서기" },
          { week: 2, title: "앞으로 나가기", content: "밀고 나가기" },
          { week: 3, title: "브레이크", content: "멈추는 법" },
          { week: 4, title: "회전", content: "커브 돌기" },
        ],
      },
      {
        id: randomUUID(),
        name: "배드민턴",
        category: "스포츠",
        description: "라켓으로 셔틀콕을 주고받는 스포츠. 반사신경과 지구력을 기를 수 있습니다.",
        difficulty: 2,
        indoorOutdoor: "both" as const,
        socialIndividual: "both" as const,
        budget: "low" as const,
        imageUrl: "/badminton.jpg",
        videoUrl: null,
        benefits: ["반사신경", "지구력", "협응력", "사회적 교류"],
        requirements: ["배드민턴 라켓", "셔틀콕", "운동화", "운동복"],
        curriculum: [
          { week: 1, title: "기본 자세", content: "라켓 잡는 법" },
          { week: 2, title: "클리어", content: "높이 쳐 올리기" },
          { week: 3, title: "스매시", content: "강하게 내려치기" },
          { week: 4, title: "드롭샷", content: "부드럽게 떨어뜨리기" },
        ],
      },
      {
        id: randomUUID(),
        name: "스키",
        category: "스포츠",
        description: "눈 덮인 슬로프를 타고 내려오는 겨울 스포츠. 균형감각과 스릴을 느낄 수 있습니다.",
        difficulty: 4,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "high" as const,
        imageUrl: "/skiing.jpg",
        videoUrl: null,
        benefits: ["균형감각", "하체 근력", "스릴", "스트레스 해소"],
        requirements: ["스키", "스키복", "헬멧", "고글", "장갑"],
        curriculum: [
          { week: 1, title: "기본 자세", content: "스키 신고 서기" },
          { week: 2, title: "직진 활주", content: "천천히 내려가기" },
          { week: 3, title: "플루크", content: "속도 줄이기" },
          { week: 4, title: "턴", content: "방향 바꾸기" },
        ],
      },
      {
        id: randomUUID(),
        name: "수상스키",
        category: "스포츠",
        description: "보트에 끌려 물 위를 타는 익스트림 스포츠. 균형감각과 전신 근력을 키울 수 있습니다.",
        difficulty: 5,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "high" as const,
        imageUrl: "/water-skiing.jpg",
        videoUrl: null,
        benefits: ["전신 근력", "균형감각", "스릴", "도전 정신"],
        requirements: ["수상스키", "구명조끼", "수영복", "보트 이용"],
        curriculum: [
          { week: 1, title: "안전 교육", content: "물에서의 안전 수칙" },
          { week: 2, title: "물 위에 서기", content: "스키로 일어서기" },
          { week: 3, title: "직진 활주", content: "균형 유지하기" },
          { week: 4, title: "턴과 점프", content: "방향 바꾸기" },
        ],
      },
      {
        id: randomUUID(),
        name: "서핑",
        category: "스포츠",
        description: "파도를 타며 즐기는 수상 스포츠. 균형감각과 도전 정신을 기를 수 있습니다.",
        difficulty: 5,
        indoorOutdoor: "outdoor" as const,
        socialIndividual: "both" as const,
        budget: "high" as const,
        imageUrl: "/surfing.jpg",
        videoUrl: null,
        benefits: ["균형감각", "전신 근력", "도전 정신", "자연 교감"],
        requirements: ["서핑보드", "웻슈트", "왁스", "리쉬코드"],
        curriculum: [
          { week: 1, title: "서핑 기초", content: "보드와 친해지기" },
          { week: 2, title: "패들링", content: "보드 위에서 헤엄치기" },
          { week: 3, title: "팝업", content: "보드 위에 서기" },
          { week: 4, title: "파도 타기", content: "작은 파도 도전" },
        ],
      },
    ];

    for (const hobby of newSportsHobbies) {
      await db.insert(hobbies).values(hobby);
      console.log(`✓ Added: ${hobby.name}`);
    }

    console.log(`\n✅ Added ${newSportsHobbies.length} new sports hobbies!`);

    const finalCount = await db.select().from(hobbies);
    console.log(`Total hobbies now: ${finalCount.length}`);

  } catch (error) {
    console.error("Error:", error);
    process.exit(1);
  }
  process.exit(0);
}

addSportsHobbies();
