import { db } from '../lib/db';
import { hobbies } from '../lib/db/schema';
import { randomUUID } from 'crypto';

const hobbyDataset = [
  // ===== 미술 카테고리 =====
  {
    name: "수채화",
    category: "미술",
    description: "물감과 붓을 이용한 아름다운 그림 그리기. 초보자도 쉽게 시작할 수 있으며, 창의력과 집중력을 향상시킵니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/수채화.png",
    benefits: ["창의력 향상", "스트레스 해소", "집중력 개선", "소근육 발달"],
    requirements: ["수채화 물감 세트", "붓", "수채화 종이", "물통"],
    curriculum: [
      { week: 1, title: "기초 도구 사용법", content: "붓 잡는 법, 물감 섞기, 종이 선택하기" },
      { week: 2, title: "기본 기법 익히기", content: "번지기, 그라데이션, 레이어링 기법" },
      { week: 3, title: "간단한 풍경화", content: "하늘, 나무, 산 그리기" },
      { week: 4, title: "정물화 그리기", content: "과일, 꽃 등 정물 표현하기" },
    ],
  },
  {
    name: "유화",
    category: "미술",
    description: "유성 물감으로 캔버스에 그림을 그리는 고급 미술 기법. 깊이 있는 색감과 질감을 표현할 수 있습니다.",
    difficulty: 4,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "high" as const,
    imageUrl: "/유화.png",
    benefits: ["예술적 표현력 향상", "인내심 기르기", "색채 감각 개발", "작품 제작의 성취감"],
    requirements: ["유화 물감", "캔버스", "붓 세트", "팔레트", "이젤"],
    curriculum: null,
  },
  {
    name: "아크릴화",
    category: "미술",
    description: "빠르게 마르는 아크릴 물감으로 다양한 표현이 가능한 회화. 수채화와 유화의 중간 성격을 지닙니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/아크릴화.png",
    benefits: ["빠른 작업 가능", "다양한 기법 활용", "창의력 발달", "스트레스 해소"],
    requirements: ["아크릴 물감", "캔버스 또는 종이", "붓", "팔레트"],
    curriculum: null,
  },
  {
    name: "색연필화",
    category: "미술",
    description: "색연필로 섬세하고 부드러운 그림을 그리는 취미. 준비물이 간단하고 어디서나 즐길 수 있습니다.",
    difficulty: 1,
    indoorOutdoor: "both" as const,
    socialIndividual: "individual" as const,
    budget: "low" as const,
    imageUrl: "/색연필화.png",
    benefits: ["손쉬운 시작", "휴대성 좋음", "섬세한 표현력", "집중력 향상"],
    requirements: ["색연필 세트", "스케치북", "지우개"],
    curriculum: null,
  },
  {
    name: "수묵화",
    category: "미술",
    description: "먹과 붓으로 한국의 전통 미를 표현하는 동양화. 여백의 미와 기운생동을 중요시합니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/수묵화.png",
    benefits: ["전통 문화 이해", "마음의 평정", "여백의 미 체득", "정신 수양"],
    requirements: ["먹", "붓", "화선지", "벼루", "물통"],
    curriculum: null,
  },
  {
    name: "민화",
    category: "미술",
    description: "조선시대부터 전해 내려오는 한국 전통 그림. 밝고 화려한 색채와 상징적 의미가 담겨 있습니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/민화.png",
    benefits: ["전통 문화 계승", "색채 감각 개발", "문화재 이해", "창작의 즐거움"],
    requirements: ["민화 물감", "한지", "붓", "밑그림"],
    curriculum: null,
  },
  {
    name: "도자기 공예",
    category: "미술",
    description: "흙을 빚어 도자기를 만드는 전통 공예. 물레를 돌리고 가마에서 굽는 전 과정을 체험합니다.",
    difficulty: 4,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/도자기공예.png",
    benefits: ["손재주 향상", "집중력 극대화", "실용적인 작품", "전통 공예 체험"],
    requirements: ["도자기 물레", "흙", "가마 사용권", "조각 도구"],
    curriculum: null,
  },
  {
    name: "캘리그라피",
    category: "미술",
    description: "붓으로 아름다운 손글씨를 쓰는 예술. 한글과 한자의 조형미를 살립니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "low" as const,
    imageUrl: "/캘리그라피.png",
    benefits: ["글씨체 개선", "집중력 향상", "예술적 감각", "실용성"],
    requirements: ["붓", "먹", "종이", "연습장"],
    curriculum: null,
  },

  // ===== 스포츠 카테고리 =====
  {
    name: "등산",
    category: "스포츠",
    description: "자연 속에서 즐기는 건강한 운동. 심폐 기능 향상과 함께 아름다운 경치를 감상할 수 있습니다.",
    difficulty: 3,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/등산.png",
    benefits: ["심폐 기능 향상", "근력 강화", "자연 치유", "사회적 교류"],
    requirements: ["등산화", "등산복", "배낭", "등산 스틱"],
    curriculum: [
      { week: 1, title: "등산 기초", content: "장비 선택, 안전 수칙, 스트레칭" },
      { week: 2, title: "초급 코스 도전", content: "낮은 산 등반, 호흡법 익히기" },
      { week: 3, title: "중급 코스 도전", content: "중급 산 등반, 체력 관리" },
      { week: 4, title: "고급 기술", content: "긴 코스 등반, 날씨 대응법" },
    ],
  },
  {
    name: "게이트볼",
    category: "스포츠",
    description: "시니어들에게 인기 있는 구기 종목. 전략적 사고와 팀워크가 중요합니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/게이트볼.png",
    benefits: ["전략적 사고", "팀워크 향상", "적당한 운동량", "사회적 교류"],
    requirements: ["게이트볼 스틱", "공", "운동화", "모자"],
    curriculum: null,
  },
  {
    name: "파크골프",
    category: "스포츠",
    description: "공원에서 즐기는 간편한 골프. 일반 골프보다 쉽고 부담 없이 즐길 수 있습니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/파크골프.png",
    benefits: ["야외 활동", "적당한 운동", "집중력 향상", "스트레스 해소"],
    requirements: ["파크골프 클럽", "공", "운동화", "장갑"],
    curriculum: null,
  },
  {
    name: "탁구",
    category: "스포츠",
    description: "실내에서 즐기는 빠른 반응 스포츠. 두뇌 회전과 순발력을 동시에 키웁니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/탁구.png",
    benefits: ["반사신경 향상", "두뇌 활동", "전신 운동", "날씨 무관"],
    requirements: ["탁구채", "탁구공", "운동화", "운동복"],
    curriculum: null,
  },
  {
    name: "배드민턴",
    category: "스포츠",
    description: "가볍고 재미있는 라켓 스포츠. 관절에 무리가 적어 시니어에게 적합합니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/배드민턴.png",
    benefits: ["전신 운동", "유연성 향상", "사교 활동", "스트레스 해소"],
    requirements: ["배드민턴 라켓", "셔틀콕", "운동화", "운동복"],
    curriculum: null,
  },
  {
    name: "수영",
    category: "스포츠",
    description: "관절에 무리가 적은 최고의 전신 운동. 사계절 내내 즐길 수 있습니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/수영.png",
    benefits: ["전신 근력 강화", "심폐 기능 향상", "관절 보호", "체중 조절"],
    requirements: ["수영복", "수경", "수모", "수건"],
    curriculum: null,
  },
  {
    name: "자전거",
    category: "스포츠",
    description: "페달을 밟으며 자연을 누비는 유산소 운동. 무릎에 부담이 적습니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/자전거.png",
    benefits: ["유산소 운동", "하체 근력", "관절 부담 적음", "여행과 결합"],
    requirements: ["자전거", "헬멧", "장갑", "안전 장비"],
    curriculum: null,
  },
  {
    name: "볼링",
    category: "스포츠",
    description: "실내에서 즐기는 대표적인 레저 스포츠. 정확성과 집중력이 필요합니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/볼링.png",
    benefits: ["집중력 향상", "전신 운동", "사교 활동", "성취감"],
    requirements: ["볼링화 (대여)", "편한 옷", "손목 보호대"],
    curriculum: null,
  },
  {
    name: "태극권",
    category: "스포츠",
    description: "느린 동작으로 몸과 마음을 다스리는 중국 무술. 명상과 운동의 조화입니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/태극권.png",
    benefits: ["균형감 향상", "유연성 증대", "스트레스 감소", "마음 안정"],
    requirements: ["편한 운동복", "운동화", "없음"],
    curriculum: null,
  },
  {
    name: "걷기",
    category: "스포츠",
    description: "가장 쉽고 안전한 운동. 매일 꾸준히 하면 건강 증진에 탁월합니다.",
    difficulty: 1,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/걷기.png",
    benefits: ["심혈관 건강", "뼈 건강", "체중 조절", "정신 건강"],
    requirements: ["편한 신발", "운동복", "물통"],
    curriculum: null,
  },

  // ===== 문화 카테고리 =====
  {
    name: "서예",
    category: "문화",
    description: "붓과 먹으로 아름다운 글씨를 쓰는 전통 예술. 마음의 평화와 집중력을 기를 수 있습니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "medium" as const,
    imageUrl: "/서예(중복).png",
    benefits: ["집중력 향상", "마음의 평화", "전통 문화 이해", "손글씨 개선"],
    requirements: ["붓", "먹", "벼루", "한지"],
    curriculum: null,
  },
  {
    name: "한문 공부",
    category: "문화",
    description: "한자와 한문 고전을 배우며 동양 문화의 깊이를 이해합니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/한문공부.png",
    benefits: ["인문학적 소양", "두뇌 활동", "고전 이해", "문화적 깊이"],
    requirements: ["한문 교재", "노트", "필기구"],
    curriculum: null,
  },
  {
    name: "시 쓰기",
    category: "문화",
    description: "일상의 감동을 시로 표현하는 문학 창작. 내면의 감정을 승화시킵니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/시쓰기.png",
    benefits: ["감성 표현", "언어 능력", "정서 안정", "창작의 기쁨"],
    requirements: ["노트", "펜", "시집"],
    curriculum: null,
  },
  {
    name: "독서토론",
    category: "문화",
    description: "좋은 책을 함께 읽고 토론하는 모임. 다양한 관점을 나누며 사고를 확장합니다.",
    difficulty: 1,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/독서토론.png",
    benefits: ["지식 확장", "사회적 교류", "비판적 사고", "소통 능력"],
    requirements: ["선정 도서", "노트", "펜"],
    curriculum: null,
  },
  {
    name: "역사 공부",
    category: "문화",
    description: "우리나라와 세계의 역사를 배우며 현재를 이해하는 통찰력을 기릅니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/역사공부.png",
    benefits: ["교양 함양", "역사 의식", "비판적 사고", "문화 이해"],
    requirements: ["역사책", "노트", "필기구"],
    curriculum: null,
  },
  {
    name: "영화 감상",
    category: "문화",
    description: "다양한 장르의 영화를 보며 문화적 소양을 넓히고 감성을 풍부하게 합니다.",
    difficulty: 1,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/영화감상.png",
    benefits: ["문화 향유", "정서 함양", "사회적 교류", "스트레스 해소"],
    requirements: ["없음"],
    curriculum: null,
  },
  {
    name: "국악",
    category: "문화",
    description: "전통 악기로 우리 음악을 배우는 취미. 가야금, 거문고, 대금 등 다양합니다.",
    difficulty: 4,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/국악.png",
    benefits: ["전통 문화 계승", "음악적 소양", "집중력", "정서 함양"],
    requirements: ["악기 (가야금 등)", "교재", "조율기"],
    curriculum: null,
  },
  {
    name: "합창",
    category: "문화",
    description: "여러 사람이 함께 노래하는 합창단 활동. 하모니를 이루는 즐거움이 있습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/합창.png",
    benefits: ["호흡 개선", "사회적 유대", "음악성 향상", "스트레스 해소"],
    requirements: ["악보", "편한 옷", "물"],
    curriculum: null,
  },
  {
    name: "사진 촬영",
    category: "문화",
    description: "카메라로 순간을 포착하는 예술. 세상을 새로운 시각으로 바라보는 법을 배웁니다.",
    difficulty: 3,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/사진촬영.png",
    benefits: ["관찰력 향상", "창의력 개발", "추억 기록", "예술적 감각"],
    requirements: ["카메라", "렌즈", "삼각대", "메모리 카드"],
    curriculum: null,
  },
  {
    name: "박물관 탐방",
    category: "문화",
    description: "다양한 박물관과 전시관을 방문하여 문화유산을 감상하고 배웁니다.",
    difficulty: 1,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/박물관탐방.png",
    benefits: ["교양 함양", "역사 이해", "문화 향유", "사회적 교류"],
    requirements: ["메모장", "편한 신발", "음료"],
    curriculum: null,
  },

  // ===== 건강 카테고리 =====
  {
    name: "요가",
    category: "건강",
    description: "몸과 마음의 균형을 찾는 운동. 유연성과 근력을 동시에 기를 수 있습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/요가.png",
    benefits: ["유연성 향상", "근력 강화", "스트레스 해소", "균형감각 개선"],
    requirements: ["요가 매트", "편한 운동복", "요가 블록"],
    curriculum: null,
  },
  {
    name: "필라테스",
    category: "건강",
    description: "코어 근육을 강화하는 운동. 자세 교정과 통증 완화에 효과적입니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/필라테스.png",
    benefits: ["코어 강화", "자세 교정", "통증 완화", "신체 인식"],
    requirements: ["요가 매트", "운동복", "소도구"],
    curriculum: null,
  },
  {
    name: "스트레칭",
    category: "건강",
    description: "몸의 유연성을 높이는 기본 운동. 부상 예방과 근육 이완에 좋습니다.",
    difficulty: 1,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/스트레칭.png",
    benefits: ["유연성 증가", "부상 예방", "혈액 순환", "근육 이완"],
    requirements: ["요가 매트", "편한 옷"],
    curriculum: null,
  },
  {
    name: "명상",
    category: "건강",
    description: "마음을 비우고 집중하는 정신 수련. 스트레스 해소와 정서 안정에 탁월합니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/명상.png",
    benefits: ["스트레스 감소", "정서 안정", "집중력 향상", "수면 개선"],
    requirements: ["명상 쿠션", "조용한 공간", "편한 옷"],
    curriculum: null,
  },
  {
    name: "단전호흡",
    category: "건강",
    description: "복식 호흡으로 기를 단련하는 한국 전통 건강법. 체력과 정신력을 기릅니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/단전호흡.png",
    benefits: ["폐활량 증가", "정신 집중", "기력 회복", "면역력 향상"],
    requirements: ["편한 옷", "조용한 공간"],
    curriculum: null,
  },
  {
    name: "경락 마사지",
    category: "건강",
    description: "경혈을 자극하여 건강을 증진하는 동양 의학. 셀프 마사지법을 배웁니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/경락마사지.png",
    benefits: ["혈액 순환", "통증 완화", "피로 회복", "면역력 증진"],
    requirements: ["마사지 도구", "경락 차트", "편한 옷"],
    curriculum: null,
  },
  {
    name: "아로마테라피",
    category: "건강",
    description: "향기로운 에센셜 오일로 심신의 건강을 돕는 자연 치유법입니다.",
    difficulty: 1,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "medium" as const,
    imageUrl: "/아로마테라피.png",
    benefits: ["스트레스 완화", "수면 개선", "기분 전환", "면역력 향상"],
    requirements: ["에센셜 오일", "디퓨저", "캐리어 오일"],
    curriculum: null,
  },
  {
    name: "춤",
    category: "건강",
    description: "음악에 맞춰 몸을 움직이는 즐거운 운동. 라인댄스, 사교댄스 등 다양합니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/춤.png",
    benefits: ["전신 운동", "리듬감 향상", "사회적 교류", "즐거움"],
    requirements: ["운동화", "편한 옷", "물"],
    curriculum: null,
  },

  // ===== 자연 카테고리 =====
  {
    name: "원예",
    category: "자연",
    description: "식물을 키우며 자연과 교감하는 활동. 정서적 안정과 성취감을 느낄 수 있습니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/원예.png",
    benefits: ["정서적 안정", "성취감", "신체 활동", "자연 교감"],
    requirements: ["화분", "흙", "씨앗/모종", "원예 도구"],
    curriculum: null,
  },
  {
    name: "텃밭 가꾸기",
    category: "자연",
    description: "직접 채소와 과일을 재배하는 도시 농업. 건강한 먹거리를 얻을 수 있습니다.",
    difficulty: 3,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/텃밭가꾸기.png",
    benefits: ["신체 활동", "건강한 먹거리", "성취감", "자연 이해"],
    requirements: ["텃밭", "농기구", "씨앗", "비료"],
    curriculum: null,
  },
  {
    name: "분재",
    category: "자연",
    description: "작은 화분에서 나무를 키우는 예술. 인내심과 섬세함이 필요합니다.",
    difficulty: 4,
    indoorOutdoor: "both" as const,
    socialIndividual: "individual" as const,
    budget: "medium" as const,
    imageUrl: "/분재.png",
    benefits: ["인내심 함양", "집중력", "예술적 감각", "정서 안정"],
    requirements: ["분재 화분", "가위", "철사", "분재용 흙"],
    curriculum: null,
  },
  {
    name: "꽃꽂이",
    category: "자연",
    description: "꽃과 식물로 아름다운 작품을 만드는 예술. 한국 전통 꽃꽂이도 배울 수 있습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/꽃꽂이.png",
    benefits: ["미적 감각", "창의력", "집중력", "계절 감각"],
    requirements: ["꽃", "화병", "가위", "꽃꽂이 도구"],
    curriculum: null,
  },
  {
    name: "버섯 재배",
    category: "자연",
    description: "실내에서 버섯을 키우는 취미. 수확의 즐거움과 건강한 먹거리를 얻습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "low" as const,
    imageUrl: "/버섯재배.png",
    benefits: ["수확의 즐거움", "건강 먹거리", "관찰력", "성취감"],
    requirements: ["버섯 재배 키트", "분무기", "조명"],
    curriculum: null,
  },
  {
    name: "수경 재배",
    category: "자연",
    description: "흙 없이 물로 식물을 키우는 현대적 방법. 깨끗하고 관리가 쉽습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "medium" as const,
    imageUrl: "/수경재배.png",
    benefits: ["깨끗한 재배", "관리 용이", "수확 가능", "관찰 재미"],
    requirements: ["수경 재배 키트", "양액", "조명", "펌프"],
    curriculum: null,
  },
  {
    name: "조경",
    category: "자연",
    description: "정원을 아름답게 꾸미는 활동. 공간을 디자인하고 식물을 배치합니다.",
    difficulty: 3,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/조경.png",
    benefits: ["창의력", "신체 활동", "미적 감각", "공간 디자인"],
    requirements: ["정원 도구", "식물", "디자인 지식", "자재"],
    curriculum: null,
  },
  {
    name: "야생화 관찰",
    category: "자연",
    description: "계절마다 피는 야생화를 찾아다니며 관찰하고 기록합니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/야생화관찰.png",
    benefits: ["자연 이해", "건강한 외출", "관찰력", "계절 감각"],
    requirements: ["야생화 도감", "카메라", "노트", "등산화"],
    curriculum: null,
  },

  // ===== 음악 카테고리 =====
  {
    name: "피아노",
    category: "음악",
    description: "건반 악기의 대표주자. 클래식부터 대중음악까지 다양한 장르를 연주할 수 있습니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "high" as const,
    imageUrl: "/피아노.png",
    benefits: ["두뇌 활동", "손가락 운동", "음악적 소양", "정서 안정"],
    requirements: ["피아노 또는 전자 피아노", "악보", "의자"],
    curriculum: null,
  },
  {
    name: "기타",
    category: "음악",
    description: "휴대하기 좋은 현악기. 반주와 솔로 연주가 모두 가능합니다.",
    difficulty: 3,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/기타.png",
    benefits: ["음악성 향상", "창작 가능", "휴대성", "사회적 교류"],
    requirements: ["기타", "튜너", "피크", "악보"],
    curriculum: null,
  },
  {
    name: "우쿨렐레",
    category: "음악",
    description: "작고 귀여운 4현 악기. 배우기 쉬워 초보자에게 인기가 많습니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/우쿨렐레.png",
    benefits: ["쉬운 학습", "휴대성", "밝은 음색", "스트레스 해소"],
    requirements: ["우쿨렐레", "튜너", "악보"],
    curriculum: null,
  },
  {
    name: "하모니카",
    category: "음악",
    description: "주머니에 넣고 다니는 관악기. 언제 어디서나 연주할 수 있습니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/하모니카.png",
    benefits: ["폐활량 증가", "휴대성", "쉬운 시작", "다양한 장르"],
    requirements: ["하모니카", "교본", "케이스"],
    curriculum: null,
  },
  {
    name: "오카리나",
    category: "음악",
    description: "도자기로 만든 관악기. 따뜻하고 부드러운 음색이 특징입니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/오카리나.png",
    benefits: ["호흡 조절", "음악성", "휴대성", "아름다운 음색"],
    requirements: ["오카리나", "악보", "손수건"],
    curriculum: null,
  },
  {
    name: "노래교실",
    category: "음악",
    description: "발성법과 가창법을 배우는 수업. 좋아하는 노래를 멋지게 부를 수 있습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "social" as const,
    budget: "medium" as const,
    imageUrl: "/노래교실.png",
    benefits: ["호흡 개선", "자신감 향상", "스트레스 해소", "사회적 교류"],
    requirements: ["없음 (또는 개인 마이크)", "악보", "물"],
    curriculum: null,
  },
  {
    name: "드럼",
    category: "음악",
    description: "리듬의 중심이 되는 타악기. 스트레스 해소에 탁월합니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/드럼.png",
    benefits: ["스트레스 해소", "리듬감", "전신 운동", "집중력"],
    requirements: ["드럼 세트", "스틱", "방음 시설"],
    curriculum: null,
  },

  // ===== 공예 카테고리 =====
  {
    name: "뜨개질",
    category: "공예",
    description: "털실로 옷이나 소품을 만드는 손뜨개. 실용적이고 창의적인 작품을 만들 수 있습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/뜨개질.png",
    benefits: ["손재주 향상", "실용적 작품", "집중력", "스트레스 해소"],
    requirements: ["뜨개바늘", "털실", "패턴북"],
    curriculum: null,
  },
  {
    name: "자수",
    category: "공예",
    description: "천에 바늘과 실로 그림을 그리는 전통 공예. 섬세하고 아름다운 작품이 탄생합니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/자수.png",
    benefits: ["집중력 극대화", "섬세함", "예술 작품", "인내심"],
    requirements: ["자수실", "바늘", "천", "자수틀"],
    curriculum: null,
  },
  {
    name: "퀼트",
    category: "공예",
    description: "천 조각을 이어 붙여 만드는 패치워크. 실용적이고 따뜻한 작품을 만듭니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/퀄트.png",
    benefits: ["창의력", "실용성", "집중력", "성취감"],
    requirements: ["천", "바늘", "실", "재봉틀"],
    curriculum: null,
  },
  {
    name: "비누 만들기",
    category: "공예",
    description: "천연 재료로 피부에 좋은 비누를 직접 만듭니다. 선물용으로도 좋습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/비누만들기.png",
    benefits: ["실용적", "창의력", "천연 제품", "선물 가능"],
    requirements: ["비누 베이스", "에센셜 오일", "몰드", "색소"],
    curriculum: null,
  },
  {
    name: "양초 공예",
    category: "공예",
    description: "다양한 모양과 향의 양초를 만드는 취미. 인테리어 소품으로 활용됩니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/양초공예.png",
    benefits: ["창의력", "인테리어", "향기 치유", "선물 가능"],
    requirements: ["왁스", "심지", "몰드", "향료", "색소"],
    curriculum: null,
  },
  {
    name: "가죽공예",
    category: "공예",
    description: "가죽으로 지갑, 가방 등을 만드는 공예. 튼튼하고 오래 쓸 수 있습니다.",
    difficulty: 4,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/가죽공예.png",
    benefits: ["실용적 작품", "내구성", "수공예 가치", "집중력"],
    requirements: ["가죽", "칼", "바늘", "실", "공구"],
    curriculum: null,
  },
  {
    name: "목공예",
    category: "공예",
    description: "나무를 깎고 다듬어 가구나 소품을 만듭니다. 남성에게 인기가 많습니다.",
    difficulty: 4,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/목공예.png",
    benefits: ["실용적", "성취감", "신체 활동", "창의력"],
    requirements: ["목재", "공구", "작업대", "안전 장비"],
    curriculum: null,
  },
  {
    name: "종이접기",
    category: "공예",
    description: "종이 한 장으로 다양한 형태를 만드는 오리가미. 두뇌 활동에 좋습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/종이접기.png",
    benefits: ["두뇌 활동", "집중력", "손재주", "창의력"],
    requirements: ["종이", "풀", "가위"],
    curriculum: null,
  },
  {
    name: "한지공예",
    category: "공예",
    description: "전통 한지로 소품과 작품을 만드는 공예. 한국의 미를 담습니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/한지공예.png",
    benefits: ["전통 문화", "섬세함", "예술 작품", "집중력"],
    requirements: ["한지", "풀", "가위", "도구"],
    curriculum: null,
  },

  // ===== 요리 카테고리 =====
  {
    name: "베이킹",
    category: "요리",
    description: "빵과 과자를 굽는 취미. 달콤한 향기와 맛있는 결과물이 기다립니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/베이킹.png",
    benefits: ["창작의 즐거움", "맛있는 결과", "선물 가능", "가족과 함께"],
    requirements: ["오븐", "재료", "도구", "레시피"],
    curriculum: null,
  },
  {
    name: "한식 요리",
    category: "요리",
    description: "전통 한식을 배우고 만드는 취미. 건강하고 맛있는 음식을 직접 만듭니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/한식요리.png",
    benefits: ["건강한 식사", "전통 계승", "가족 만족", "실용적"],
    requirements: ["조리 도구", "재료", "레시피"],
    curriculum: null,
  },
  {
    name: "발효 음식",
    category: "요리",
    description: "김치, 장류 등 발효 음식을 만듭니다. 건강에 좋고 보관도 가능합니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/발표음식.png",
    benefits: ["건강식", "장기 보관", "전통 계승", "경제적"],
    requirements: ["항아리", "재료", "레시피", "보관 공간"],
    curriculum: null,
  },
  {
    name: "커피 로스팅",
    category: "요리",
    description: "생두를 직접 볶아 나만의 커피를 만듭니다. 향과 맛을 조절할 수 있습니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/커피로스팅.png",
    benefits: ["향미 체험", "경제적", "취향 저격", "여유"],
    requirements: ["로스터", "생두", "그라인더", "드립 도구"],
    curriculum: null,
  },
  {
    name: "차 문화",
    category: "요리",
    description: "다양한 차를 우리고 음미하는 취미. 여유와 건강을 동시에 얻습니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/차문화.png",
    benefits: ["정서 안정", "건강 증진", "문화 이해", "여유"],
    requirements: ["다기", "차", "주전자", "잔"],
    curriculum: null,
  },

  // ===== 기술 카테고리 =====
  {
    name: "컴퓨터 활용",
    category: "기술",
    description: "워드, 엑셀, 인터넷 등 컴퓨터 기본 활용법을 배웁니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/컴퓨터활용.png",
    benefits: ["실생활 활용", "정보 접근", "소통 도구", "두뇌 활동"],
    requirements: ["컴퓨터", "인터넷", "교재"],
    curriculum: null,
  },
  {
    name: "스마트폰 활용",
    category: "기술",
    description: "스마트폰의 다양한 기능과 앱 사용법을 배웁니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "low" as const,
    imageUrl: "/스마트폰활용.png",
    benefits: ["편리한 생활", "소통", "정보 활용", "자립"],
    requirements: ["스마트폰", "충전기"],
    curriculum: null,
  },
  {
    name: "영상 편집",
    category: "기술",
    description: "동영상을 촬영하고 편집하여 작품을 만듭니다. 유튜브 등에 활용 가능합니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/영상편집.png",
    benefits: ["창작 활동", "추억 보존", "소통", "두뇌 활동"],
    requirements: ["컴퓨터", "편집 프로그램", "카메라"],
    curriculum: null,
  },
  {
    name: "블로그 운영",
    category: "기술",
    description: "개인 블로그를 만들어 일상과 취미를 기록하고 공유합니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "low" as const,
    imageUrl: "/블로그운영.png",
    benefits: ["기록 보존", "소통", "정보 공유", "자기 표현"],
    requirements: ["컴퓨터", "인터넷", "카메라"],
    curriculum: null,
  },

  // ===== 언어 카테고리 =====
  {
    name: "영어 회화",
    category: "언어",
    description: "실생활에서 사용하는 영어 회화를 배웁니다. 여행이나 외국인과의 소통에 유용합니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/영어회화.png",
    benefits: ["의사소통", "여행 편의", "두뇌 활동", "자신감"],
    requirements: ["교재", "노트", "음성 파일"],
    curriculum: null,
  },
  {
    name: "중국어",
    category: "언어",
    description: "가까운 이웃 나라의 언어를 배웁니다. 중국 문화 이해에도 도움이 됩니다.",
    difficulty: 4,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/중국어.png",
    benefits: ["새로운 언어", "문화 이해", "두뇌 활동", "소통"],
    requirements: ["교재", "사전", "음성 파일"],
    curriculum: null,
  },
  {
    name: "일본어",
    category: "언어",
    description: "일본 여행이나 문화 콘텐츠 이해에 유용한 일본어를 배웁니다.",
    difficulty: 3,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/일본어.png",
    benefits: ["여행 편의", "문화 향유", "두뇌 자극", "새로운 도전"],
    requirements: ["교재", "노트", "음성 파일"],
    curriculum: null,
  },

  // ===== 여가 카테고리 =====
  {
    name: "바둑",
    category: "여가",
    description: "흑과 백의 대결, 깊은 전략이 필요한 두뇌 게임입니다.",
    difficulty: 4,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/바둑.png",
    benefits: ["전략적 사고", "집중력", "인내심", "사회적 교류"],
    requirements: ["바둑판", "바둑돌"],
    curriculum: null,
  },
  {
    name: "장기",
    category: "여가",
    description: "한국 전통 보드 게임. 두뇌 회전과 전략적 사고를 기릅니다.",
    difficulty: 3,
    indoorOutdoor: "both" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/장기.png",
    benefits: ["두뇌 활동", "전략 수립", "사회적 교류", "전통 문화"],
    requirements: ["장기판", "장기알"],
    curriculum: null,
  },
  {
    name: "퍼즐",
    category: "여가",
    description: "직소 퍼즐이나 큐브 등 다양한 퍼즐을 맞추며 집중력을 기릅니다.",
    difficulty: 2,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "individual" as const,
    budget: "low" as const,
    imageUrl: "/퍼즐.png",
    benefits: ["집중력", "인내심", "성취감", "스트레스 해소"],
    requirements: ["퍼즐"],
    curriculum: null,
  },
  {
    name: "낚시",
    category: "여가",
    description: "자연 속에서 물고기를 잡는 여유로운 취미. 기다림의 미학을 배웁니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/낚시.png",
    benefits: ["여유", "인내심", "자연 교감", "신선한 먹거리"],
    requirements: ["낚싯대", "릴", "미끼", "의자"],
    curriculum: null,
  },
  {
    name: "여행",
    category: "여가",
    description: "국내외 여행을 다니며 새로운 경험을 쌓습니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/여행.png",
    benefits: ["새로운 경험", "문화 이해", "추억 쌓기", "스트레스 해소"],
    requirements: ["여행 가방", "카메라", "편한 신발"],
    curriculum: null,
  },
  {
    name: "천체 관측",
    category: "여가",
    description: "망원경으로 별과 달, 행성을 관찰하는 낭만적인 취미입니다.",
    difficulty: 3,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "high" as const,
    imageUrl: "/천체관측.png",
    benefits: ["우주 이해", "낭만", "관찰력", "지적 호기심"],
    requirements: ["망원경", "성도", "의자", "손전등"],
    curriculum: null,
  },
  {
    name: "조류 관찰",
    category: "여가",
    description: "쌍안경으로 새를 관찰하고 기록하는 버드워칭입니다.",
    difficulty: 2,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "both" as const,
    budget: "medium" as const,
    imageUrl: "/조류관찰.png",
    benefits: ["자연 이해", "관찰력", "야외 활동", "평화로움"],
    requirements: ["쌍안경", "조류 도감", "노트", "카메라"],
    curriculum: null,
  },

  // ===== 봉사 카테고리 =====
  {
    name: "독서 지도",
    category: "봉사",
    description: "아이들에게 책을 읽어주고 독서 습관을 길러주는 봉사활동입니다.",
    difficulty: 1,
    indoorOutdoor: "indoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/독서지도.png",
    benefits: ["보람", "세대 교류", "지식 나눔", "사회 공헌"],
    requirements: ["동화책", "열정"],
    curriculum: null,
  },
  {
    name: "멘토링",
    category: "봉사",
    description: "자신의 경험과 지식을 젊은 세대와 나누는 활동입니다.",
    difficulty: 2,
    indoorOutdoor: "both" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/멘토링.png",
    benefits: ["보람", "경험 공유", "세대 소통", "자존감"],
    requirements: ["경험", "소통 능력"],
    curriculum: null,
  },
  {
    name: "환경 보호",
    category: "봉사",
    description: "지역 청소, 분리수거 캠페인 등 환경을 지키는 활동입니다.",
    difficulty: 1,
    indoorOutdoor: "outdoor" as const,
    socialIndividual: "social" as const,
    budget: "low" as const,
    imageUrl: "/환경보호.png",
    benefits: ["사회 공헌", "운동 효과", "보람", "공동체 의식"],
    requirements: ["장갑", "집게", "쓰레기봉투"],
    curriculum: null,
  },
];

async function seedHobbies() {
  try {
    console.log(`대량 취미 데이터 삽입 시작... (총 ${hobbyDataset.length}개)`);

    // 기존 데이터 확인
    const existingHobbies = await db.query.hobbies.findMany();
    console.log(`현재 데이터베이스에 ${existingHobbies.length}개의 취미가 있습니다.`);

    // 배치 단위로 삽입 (한 번에 너무 많이 하면 부하가 걸릴 수 있음)
    const batchSize = 10;
    let inserted = 0;

    for (let i = 0; i < hobbyDataset.length; i += batchSize) {
      const batch = hobbyDataset.slice(i, i + batchSize);

      const dataToInsert = batch.map(hobby => ({
        id: randomUUID(),
        ...hobby,
        videoUrl: null,
      }));

      await db.insert(hobbies).values(dataToInsert);
      inserted += dataToInsert.length;
      console.log(`진행률: ${inserted}/${hobbyDataset.length} (${Math.round(inserted/hobbyDataset.length*100)}%)`);
    }

    console.log(`\n✅ 성공적으로 ${inserted}개의 취미 데이터를 삽입했습니다!`);

    // 카테고리별 통계
    const finalHobbies = await db.query.hobbies.findMany();
    const categoryStats: { [key: string]: number } = {};

    finalHobbies.forEach(hobby => {
      categoryStats[hobby.category] = (categoryStats[hobby.category] || 0) + 1;
    });

    console.log("\n📊 카테고리별 통계:");
    Object.entries(categoryStats).sort((a, b) => b[1] - a[1]).forEach(([category, count]) => {
      console.log(`  ${category}: ${count}개`);
    });

  } catch (error) {
    console.error("에러 발생:", error);
    process.exit(1);
  }

  process.exit(0);
}

seedHobbies();
